'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from 'next/navigation';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ["latin"] });

//export const metadata = {
//  title: "RailNav",
//  description: "Generated by create next app",
//};

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // Don't render the Navbar on the home page
  const isHomePage = pathname === '/';

  return (
    <html lang="en">
      <body className={inter.className}>
        {!isHomePage && <Navbar />}
        {children}
      </body>
    </html>
  );
}
